### ISSUE TITLE
update dependencies

### ISSUE THREAD

**Issue by pbrandone** [Significa/significa.co#110]

**Comment by danilowoz** [comment]
I'm not sure if I agree with it. Any new feature is required or there is any security issue opened? 
I think it is unnecessary work and it could break the current codebase because we have to trust that

**Comment by danilowoz** [comment]
I'm not sure if I agree with it. 
Any new feature is required or there is any security issue opened?

I think it is unnecessary work and it could break the current codebase. Because we have to trust that the maintainers of dependencies haven't delivered any breakchange. So the best approach for that is updated the only package we need new features or fix bugs, where we know the scope of the package or security issues (the most important one).
