### ISSUE TITLE
How does one import data to prismic?

### ISSUE THREAD

**Issue by kuttim** [Significa/significa.co#178]
Hey, great project!
Been seeing some issues with data not being in prismic, any plans to update the readme so people would know how to import the data needed to prismic or am I missing something very stupid?

Thanks!

**Comment by pbrandone** [comment]
Hi @kuttim thanks!

Unfortunately, we recently migrated to `gatsby-source-prismic` that requires us to define an access token in `gatsby-config.js`

Now that I think of it, this token could probably be exposed (given it only gives access to master in Prismic)

Let us check and, if that's the case, we'll update our config to include the hard-coded token (instead of env variable)

**Comment by rogeriotoledo** [comment]
Hi @pbrandone,

I'd like to take a peek at significa.co source-code. I'm specially interested in the Handbook code.
I have no experience with Prismic and I'm now sure how to adjust the API Token (accessToken) in gatsby-config.js.

I added a random API Token in order to build the project, but I've got the following error when I tried to load the Handbook page:
TypeError: Cannot read property 'data' of undefined (take a look at the attached screenshot).

Can you give me a hand?

Obrigado!
![CleanShot 2020-11-29 at 23 11 06](https://user-images.githubusercontent.com/872638/100561702-535db500-3298-11eb-85bf-dec7cdf8bffd.png)

**Comment by danilowoz** [comment]
@rogeriotoledo @deephut please see https://github.com/significa/significa.co/pull/190#pullrequestreview-544898346
